name: 1.1$(rev:.r) # build numbering format

variables:
  BuildConfiguration: 'Release'
  FolderToPack: 'Application'
  ApplyDockerstack: False

resources:
  repositories:
  - repository: ALMStuff
    type: github
    name: DrMueller/ALMStuff
    ref: refs/heads/master
    endpoint: GitHub-DrMueller

jobs:
- job: 'BuildAndPublishToNuGet'
  displayName: 'Build and publish to NuGet'
  pool:
    name: Hosted Ubuntu 1604
  steps:
  - template: AzureDevOps/BuildTemplates/NetCore/Steps/Initialize_And_Test.yaml@ALMStuff
    parameters:
      BuildConfiguration: $(BuildConfiguration)

  - task: YodLabs.VariableTasks.SetVariable.SetVariable@0
    displayName: 'Set Variable ImageName to $(Build.Repository.Name) with toLowerCase applied'
    inputs:
      variableName: ImageName

      value: '$(Build.Repository.Name)'

      transform: toLowerCase

  - task: YodLabs.VariableTasks.SetVariable.SetVariable@0
    displayName: 'Set Variable ImageName to $(ImageName) with replace applied'
    inputs:
      variableName: ImageName
      value: '$(ImageName)'
      transform: replace
      searchValue: '\.'
      newValue: '-'

  - task: Docker@0
    displayName: 'Build Docker Image'
    inputs:
      containerregistrytype: 'Container Registry'
      dockerRegistryConnection: DockerHub
      imageName: '$(ImageName)'
      additionalImageTags: '$(Build.BuildNumber)'
      includeLatestTag: true

  - task: Docker@0
    displayName: 'Push Docker Image'
    inputs:
      containerregistrytype: 'Container Registry'
      dockerRegistryConnection: DockerHub
      action: 'Push an image'
      imageName: '$(ImageName)'
      additionalImageTags: '$(Build.BuildNumber)'
      includeLatestTag: true

  - ${{ if eq(ApplyDockerstack, true) }}:
    - task: powershell@2
      displayName: 'Update DockerStack'
      inputs:
        targetType: filePath
        filePath: './Scripts/Update-Dockerstack.ps1' 
        arguments: '-repositoryLocalPath $(Build.Repository.LocalPath) -imageName $(ImageName):$(Build.BuildNumber)'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish DockerStack'
      inputs:
        PathtoPublish: 'docker-stack.yml'

