name: 1.0$(rev:.r) # build numbering format

resources:
  repositories:
  - repository: ALMStuff
    type: github
    name: DrMueller/ALMStuff
    ref: refs/heads/master
    endpoint: GitHub-DrMueller

queue:
  name: Hosted Ubuntu 1604

variables:
  BuildConfiguration: 'Release'
  FolderToPublish: 'Application'
  ApplyDockerstack: false

jobs:
- job: 'BuildAndPublishAsArtifact'
  displayName: 'Build and save zipped Artifact'
  pool:
    name: Default
  steps:
  - template: AzureDevOps/BuildTemplates/NetCore/Steps/Initialize_And_Test.yaml@ALMStuff
    parameters:
      buildConfiguration: $(BuildConfiguration)
  - template: AzureDevOps/BuildTemplates/NetCore/Steps/Publish.yaml@ALMStuff
    parameters:
      BuildConfiguration: $(BuildConfiguration)
      FolderToPublish: $(FolderToPublish)
  - template: AzureDevOps/BuildTemplates/NetCore/Steps/Zip_And_Save_Artifact.yaml@ALMStuff
