name: 1.1$(rev:.r) # build numbering format

variables:
  BuildConfiguration: 'Release'
  FolderToPack: 'Application'

resources:
  repositories:
  - repository: ALMStuff
    type: github
    name: DrMueller/ALMStuff
    ref: refs/heads/master
    endpoint: GitHub-DrMueller

jobs:
- job: 'BuildAndPublishToNuGet'
  displayName: 'Build and publish to NuGet'
  pool:
    name: 'Default'
  steps:
  - template: AzureDevOps/BuildTemplates/NetCore/Steps/Initialize_And_Test.yaml@ALMStuff
    parameters:
      BuildConfiguration: $(BuildConfiguration)
